# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-19 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lhcbpr_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Executable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='platform',
            old_name='cmtconfig',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='requestedplatform',
            old_name='cmtconfig',
            new_name='config',
        ),
        migrations.RemoveField(
            model_name='addedresult',
            name='old_id',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='old_id',
        ),
        migrations.RemoveField(
            model_name='handler',
            name='old_id',
        ),
        migrations.RemoveField(
            model_name='handlerresult',
            name='old_id',
        ),
        migrations.RemoveField(
            model_name='host',
            name='old_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='old_id',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='old_id',
        ),
        migrations.RemoveField(
            model_name='jobhandler',
            name='old_id',
        ),
        migrations.RemoveField(
            model_name='jobresult',
            name='old_id',
        ),
        migrations.RemoveField(
            model_name='option',
            name='is_standalone',
        ),
        migrations.RemoveField(
            model_name='option',
            name='old_id',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='old_id',
        ),
        migrations.RemoveField(
            model_name='setupproject',
            name='old_id',
        ),
        migrations.RemoveField(
            model_name='requestedplatform',
            name='old_id',
        ),
        migrations.AlterUniqueTogether(
            name='requestedplatform',
            unique_together=set([('job_description', 'config')]),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='execulatble',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobdescriptions', to='lhcbpr_api.Executable'),
        ),
        migrations.AddField(
            model_name='option',
            name='executable',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='lhcbpr_api.Executable'),
        ),
    ]
