#!/usr/bin/env bash

./site/manage.py migrate

check=$(./site/manage.py dumpdata  --pks 1 lhcbpr_api.jobresult| tail -n1)
if [ "$check" == "[]" ] ;
then
  dump="fixtures/dump10.json"
  echo "Load $dump"
  ./site/manage.py loaddata $dump
fi
