#!/bin/sh

if [ $# -ne 0 ]
then
    . envs/$1.env
fi

API_PORT=${DJANGO_HTTP_PORT:-80}
API_HOST=0.0.0.0

echo "Bootstrap..."
./scripts/bootstrap

echo "Run server at ${API_HOST}:${API_PORT}..."
./site/manage.py runserver ${API_HOST}:${API_PORT}
